### ISSUE TITLE
USER STORY: Poll to enhance interactivity

### ISSUE THREAD

**Issue by DevFabrizio** [DevFabrizio/My-first-Agile-Workspace#3]
As a **runner** I can **vote on the best track and time** so that **will know which track to go to and when**

### Acceptance Criteria
* Ability to vote best track
* Ability to vote best time of the day to run 
* Ability to post poll anonymously

## Tasks
- [ ] Create dropdown menu with the options for the best track
- [ ] Create dropdown menu with the time options
- [ ] Create checkbox to select anonymity
